### ISSUE TITLE
No display for vacations

### ISSUE THREAD

**Issue by marjev** [vladimyr/dajyst.app#1]
As a user I would like to see the vacation notice displayed somewhere on the UI.

**Comment by vladimyr** [comment]
I'm not sure I follow you :confused: 

This is essentially facebook posts scraper with parser that _understands_ two different categories of posts:
1. standard (with blue margin & light blue background)
2. menu listings

Vacation notice is already there:
![image](https://user-images.githubusercontent.com/1170440/41498553-b574698c-7170-11e8-8a92-a67647f4cd6b.png)

You are asking for implementing 3rd category?
Or you want app to show some sort of _we are closed_ notification once parser hits vacation announcement?

**Comment by vladimyr** [comment]
Is this any better?
![image](https://user-images.githubusercontent.com/1170440/41498707-8b1504c2-7174-11e8-9cd3-66fbf805b0ab.png)

If post content matches `/ne(?:[čćc]e)?\s+radi/i` it is recognized as `closed-notice`, gets appropriate classname and different styling :grey_question:

**Comment by vladimyr** [comment]
Because you asked for it :tada: 

<img width="400" src="https://user-images.githubusercontent.com/1170440/41499308-2b275312-717e-11e8-8ee2-2311bc03980d.png">

**Comment by marjev** [comment]
thanks, much better.  👍

**Comment by vladimyr** [comment]
Glad to help :bowtie:
Feels nice that someone actually uses this :upside_down_face:
